# Generated by Django 6.0 on 2025-12-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('operador', models.CharField(max_length=255)),
                ('placas', models.CharField(blank=True, max_length=50)),
                ('carta_tif', models.BooleanField(default=False)),
                ('factura', models.BooleanField(default=False)),
                ('copias_tif_porteo', models.BooleanField(default=False)),
                ('orden_compra', models.BooleanField(default=False)),
                ('confirmacion_cita', models.BooleanField(default=False)),
                ('control_embarque', models.BooleanField(default=False)),
                ('other_name', models.CharField(blank=True, max_length=255)),
                ('other_present', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
